@startuml

title Abstract Factoryクラス図

note as memo
    図形を生成するプログラム。
    プレーンテキストでも、SVGでも出力できる。

    図形を生成する側はFactoryクラスの振る舞いについて知っていれば必要な図形を生成できる。
    図形が増えたときはFactoryクラスを追加する。
endnote

class DiagramFactory {
    "図形生成インスタンスのファクトリの基底クラス。具象クラスでもある。"
    --
    ダイアグラムを生成する(横幅: Integer, 縦幅: Integer)
    四角形を生成する(x座標: Integer, y座標: Integer, 横幅: Integer, 縦幅: Integer, 四角形を埋める色: String, stroke: String)
    テキストを生成する(x座標: Integer, y座標: Integer, テキスト文: String, フォントサイズ: Integer)
}

class DiagramFactory.Diagram {
    "Diagram(図形)"
    --
    追加する(コンポーネント: Component)
}

class DiagramFactory.Component {
    "Component(図形の構成要素)"
    --

}

class DiagramFactory.Rectangle {
    "Rectangle(四角形)"
    --
}

class DiagramFactory.Text {
    "Text(テキスト)"
    --
}

DiagramFactory --> DiagramFactory.Diagram
DiagramFactory --> DiagramFactory.Rectangle
DiagramFactory --> DiagramFactory.Text
DiagramFactory.Diagram *-- DiagramFactory.Component

DiagramFactory.Text --|> DiagramFactory.Component
DiagramFactory.Rectangle --|> DiagramFactory.Component

class SVGDiagramFactory {
    "SVGDiagramFactory (ダイアグラムファクトリ)"
}

class SVGDiagramFactory.Diagram {
    "Diagram(図形)"
    --
    追加する(コンポーネント: component)
}

class SVGDiagramFactory.Component {
    "Component(図形の構成要素)"
    --
}

class SVGDiagramFactory.Rectangle {
    "Rectangle(四角形)"
    --
}

class SVGDiagramFactory.Text {
    "Text(テキスト)"
    --
}

SVGDiagramFactory --> SVGDiagramFactory.Diagram
SVGDiagramFactory --> SVGDiagramFactory.Rectangle
SVGDiagramFactory --> SVGDiagramFactory.Text
SVGDiagramFactory.Diagram *-- SVGDiagramFactory.Component

SVGDiagramFactory.Text --|> SVGDiagramFactory.Component
SVGDiagramFactory.Rectangle --|> SVGDiagramFactory.Component

SVGDiagramFactory --|> DiagramFactory
@enduml